<?php

/**
 * @file
 * Module used to house customizations for Simon Fraser University.
 */

define('SFUDORA_INGEST_PATH', 'sfudora/ingest');
define('SFUDORA_INGEST_UPDATE_PATH', 'sfudora/update/ingest/%');
define('SFUDORA_XACML_FOLDER', '/xacml');
define('SFUDORA_AJXP_URI', 'http://ajaxplorer.info');
define('SFUDORA_AJXP_FRAME','sfudora/ajaxplorer');
/**
 * Implements hook_menu().
 */
function sfudora_menu() {
  $items = array();

  $items[SFUDORA_INGEST_PATH] = array(
    'title' => 'SFU Ingest',
    'access callback' => TRUE,
    'page callback' => 'sfudora_ajaxplorer_ingest',
    'file' => 'includes/ajaxplorer_ingest.inc',
    'type' => MENU_CALLBACK,
  );
  $items[SFUDORA_INGEST_UPDATE_PATH] = array(
    'title' => 'SFU Ingest',
    'access callback' => TRUE,
    'page callback' => 'sfudora_ajaxplorer_update_ingest',
    'page arguments' => array(3),
    'file' => 'includes/ajaxplorer_ingest.inc',
    'type' => MENU_CALLBACK,
  );
  $items[SFUDORA_AJXP_FRAME] = array (
    'title'=> 'SFU Ajaxplorer Frame',
    'access callback' => TRUE,
    'page callback' => 'sfudora_ajaxplorer_frame',
    'type' => MENU_CALLBACK,
  );
  $items['admin/islandora/sfudora'] = array(
    'title' => 'Simon Fraser University Settings',
    'description' => 'Configure settings for the sfudora module.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('sfudora_admin_form'),
    'access arguments' => array('administer site configuration'),
    'file' => 'includes/sfudora.admin.form.inc',
  );

  return $items;
}

/**
 * Implements hook_islandora_required_objects().
 */
function sfudora_islandora_required_objects(IslandoraTuque $connection) {
  $module_path = drupal_get_path('module', 'sfudora');
  // SFU Generic Content Model.
  $generic_cmodel = $connection->repository->constructObject('sfu:genericCModel');
  $generic_cmodel->owner = 'fedoraAdmin';
  $generic_cmodel->label = 'Generic file content model for Simon Fraser University';
  $generic_cmodel->models = 'fedora-system:ContentModel-3.0';
  $datastream = $generic_cmodel->constructDatastream('DS-COMPOSITE-MODEL', 'X');
  $datastream->label = 'DS-COMPOSITE-MODEL';
  $datastream->mimetype = 'text/xml';
  $datastream->setContentFromFile("$module_path/data/datastreams/generic_CModel/DS-COMPOSITE-MODEL.xml", FALSE);
  $generic_cmodel->ingestDatastream($datastream);

  return array(
    'sfudora' => array(
      'title' => 'Simon Fraser University',
      'objects' => array(
        $generic_cmodel,
      ),
    ),
  );
}

function sfudora_ajaxplorer_frame()
{
  drupal_set_title("AjaXplorer");
  $output = array();
  $module_path = drupal_get_path('module','sfudora');
  drupal_add_js("$module_path/js/ajaxplorer_frame.js");
  drupal_add_css("$module_path/css/ajaxplorer_frame.css");
  $serverBaseURL=$_SERVER['HTTP_HOST'];
  $sfu_path = "http://".$serverBaseURL."/".variable_get('ajxp_path', 'ajaxplorer');
  $output['Simon Fraser University AjaXplorer'] = array (
     '#markup' =>"<iframe id=\"ajaxplorer_frame\" src=\"$sfu_path\"></iframe>", 
  ) ;
  return $output;
}